apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    name: client
    app: client
spec:
      containers:
      - name: client
        image: esotirovic/client-app
        ports:
        - containerPort: 80