apiVersion: v1
kind: Pod
metadata:
  name: webservice
  labels:
    name: webservice
    app: webservice
spec:
      containers:
      - name: webservice
        image: esotirovic/webservice
        ports:
        - containerPort: 8081

